[logging]
version = 1
disable_existing_loggers = false

[logging.formatters.simple]
format = "[{asctime}] [{processName}:{name}] [{filename}:{lineno}] {levelname}: {message}"
style = "{"

[logging.handlers.console]
level = "INFO"
formatter = "simple"
class = "logging.StreamHandler"
stream = "ext://sys.stdout"

[logging.handlers.file]
formatter = "simple"
class = "logging.handlers.RotatingFileHandler"
filename = "demo.log"
maxBytes = 10485760  # 10MB
backupCount = 3

[logging.root]
level = "DEBUG"
handlers = ["console", "file"]
