version = 1
disable_existing_loggers = false

[formatters.simple]
format = "[{asctime}] [{processName}:{name}] [{filename}:{lineno}] {levelname}: {message}"
style = "{"

[handlers.console]
level = "INFO"
formatter = "simple"
class = "hmull.app.TqdmStreamHandler"

[handlers.file]
formatter = "simple"
class = "logging.handlers.RotatingFileHandler"
filename = "demo.log"
maxBytes = 10485760  # 10MB
backupCount = 3

[root]
level = "DEBUG"
handlers = ["console", "file"]
